### ISSUE TITLE
Language selection and Theme selection have disappeared 

### ISSUE THREAD

**Issue by bluezed** [doubleangels/NextDNSManager#100]
The app just updated to 4.10.1 from PlayStore and I just noticed that the language and theme selection have disappeared.

I'm on a Xiaomi Mi Note 10 Lite (MIUI 13.0.6, Android 12).

Was that a deliberate removal?

I like to use apps in a different language to my system default and since the top and bottom of the app are in a light blue I prefer the light theme for it.

Could those options be added again please?

Thanks!

**Comment by doubleangels** [comment]
Hi! 

Thanks for reaching out. Those were deliberate removals. The theme selection as present before was the source of a large number of bugs so that feature will likely be reworked and added back to the future. However, going forward the app will use the default system language. I am looking at using the per-app language feature available in Android 13+ but that would help you much unfortunately. 

I will leave this issue open and update you about when the theme selection has been re-added (likely in the next month or so). I can also look at making the dark theme's bottom bar match more of the dark theme itself.

**Comment by bluezed** [comment]
Thanks for the quick reply, appreciate it 👍

If the top and bottom match better with the dark theme I'd be happy with that and wouldn't need the light theme any more.

Shame about the language selection. Guess I'll need a new phone then... 😄

**Comment by doubleangels** [comment]
The top and bottom bar are using material you colors, but I will take another look at the bottom one for sure as well as better support for versions of Android that don't support material you. I appear to have overlooked that. Thanks for bringing it to my attention. 

Sorry about the language support, changing locales programmatically is just very buggy and not recommended any longer. :)

**Comment by doubleangels** [comment]
I've made a few changes as discussed. They will roll out shortly, as version 4.10.2. 

Also, good news! It turns out that per-app languages are backwards compatible with <Android 13, so it should work with you. Please let me know if you have any issues.

**Comment by bluezed** [comment]
v4.10.2 just dropped and the colour match is much better now. Can live with dark theme now 😄
Thanks for the quick update!
