### ISSUE TITLE
v5.0.0 (Pre-Release) APK is 557MB

### ISSUE THREAD

**Issue by hirenshah** [doubleangels/NextDNSManager#189]
Surely that isn't right?

**Comment by doubleangels** [comment]
Hi @hirenshah,

Yes, the pre-release APK is quite large. The update to 5.0.0 no longer uses Android's WebView and instead uses Firefox's GeckoView, as it's more secure and customizable. Unfortunately, that means that the APK contains all the code for a web browser within it, so that's why it's so large. In subsequent pre-releases, I will reduce this size, but I wanted to get this beta version out to see how it performs. On Google Play, if you join the beta track, the download is much smaller.

**Comment by doubleangels** [comment]
Pre-release 5.0.0 has been pulled temporarily due to a runtime error.

**Comment by doubleangels** [comment]
Pre-release 5.0.0-beta1 is rolling out shortly, this should have a smaller APK size and fixes the runtime error.
