### ISSUE TITLE
Apple.nextdns.io unable to download configuration profile. (also, some other feedback) 

### ISSUE THREAD

**Issue by LetsGoOpenSource** [doubleangels/NextDNSManager#5]
App ver: 4.2.6
Android ver: 10 Go
1. In the iOS setup guide, the hyperlink to apple.nextdns.io opens the configuration page but the download button does not work. Would it be possible to add this functionality? 
2.  It would be nice if a toggle to hide the secure DNS indicator in the top left was added? I use the Nebulo app so the indicator never shows useful information.
3. Could descriptions be added in the Preferences page to identify what each domain is used for. For instance, what is used for push notifications.
4. Invoice and API text in the Account page appear black. Could those be changed to white for legibility? 
5. Do you plan to ever use the updated NextDNS logo? Or are you avoiding doing so for legal reasons?

These are small nitpicks, but otherwise a great app! Thank you!

**Comment by mtverlee** [comment]
Thanks for the feedback! I'd be happy to look at the bug you mentioned with iOS setup. Thanks for the feedback on the other items, I'll take them into consideration.

**Comment by mtverlee** [comment]
Hello @LetsGoOpenSource,

Thanks for your feedback! The iOS Configuration download issue was fixed in 47e5638a0e1c8a5c386b47642134859ae5b9085e. The invoice and API text bug was also fixed in 3b3f1e182e53e932076d686a7c8a856233fd8cec. These changes are live and should be rolling out shortly.

The other items which you mentioned are great, but will take a little bit more time to implement. I will happily add these in upcoming updates and update here. Thanks again for your feedback!

**Comment by doubleangels** [comment]
After careful consideration, I've to leave the connection status without the ability to toggle it. Closing for now!
